<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJIheenx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJIheenx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJIheenx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJIheenx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJIheenx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'JIheenx',
    'container.build_id' => '6cf7292f',
    'container.build_time' => 1538653761,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJIheenx');
